name: Deploy to GitHub Pages

on:
  push:
    branches: ["main", "master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lấy source code
        uses: actions/checkout@v4

      - name: Cài đặt Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cài đặt thư viện
        run: npm ci

      - name: Build ứng dụng (Tích hợp API Key từ Secrets)
        run: npm run build
        env:
          VITE_TMDB_API_KEY: ${{ secrets.VITE_TMDB_API_KEY }}
          VITE_TMDB_BASE_URL: ${{ secrets.VITE_TMDB_BASE_URL }}

      - name: Tải file dist lên máy chủ Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Triển khai lên GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4